-- LEVEL 4 — Business Questions

-- Q38: Total quantity sold for each product
SELECT p.product_name, SUM(oi.quantity) AS total_quantity
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name;

-- Q39: Total revenue generated by each product (quantity * unit_price * (1 - discount))
SELECT p.product_name,
       SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) AS total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name;

-- Q40: Top 5 products by revenue
SELECT p.product_name,
       SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) AS total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- Q41: Total revenue generated by each category
SELECT cat.category_name,
       SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) AS total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN categories cat ON p.category_id = cat.category_id
GROUP BY cat.category_name;

-- Q42: Number of orders placed by each customer
SELECT c.customer_name, COUNT(o.order_id) AS order_count
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name;

-- Q43: Customers who have placed more than 1 order
SELECT c.customer_name, COUNT(o.order_id) AS order_count
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING COUNT(o.order_id) > 1;

-- Q44: The customer who generated the highest total revenue
SELECT c.customer_name,
       SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_name
ORDER BY total_revenue DESC
LIMIT 1;

-- Q45: The employee who handled the highest number of orders
SELECT e.employee_name, COUNT(o.order_id) AS order_count
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id
GROUP BY e.employee_name
ORDER BY order_count DESC
LIMIT 1;

-- Q46: The employee who generated the highest order value
SELECT e.employee_name,
       SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) AS total_value
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY e.employee_name
ORDER BY total_value DESC
LIMIT 1;

-- Q47: Most popular product based on total quantity sold
SELECT p.product_name, SUM(oi.quantity) AS total_quantity
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC
LIMIT 1;

-- Q48: Most popular category based on total quantity sold
SELECT cat.category_name, SUM(oi.quantity) AS total_quantity
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN categories cat ON p.category_id = cat.category_id
GROUP BY cat.category_name
ORDER BY total_quantity DESC
LIMIT 1;

-- Q49: Total revenue for each month
SELECT strftime('%Y-%m', o.order_date) AS month,
       SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) AS total_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;

-- Q50: Total revenue generated from Premium customers
SELECT SUM(oi.quantity * oi.unit_price * (1 - oi.discount)) AS premium_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
WHERE c.customer_type = 'Premium';
